[advisories]
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
exceptions = [
  { allow = ["NCSA"], crate = "libfuzzer-sys@0.4.13" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
